import streamlit as st
st.title('About Income Prediction Project')

st.write("An individual’s annual income results from various factors. Intuitively, it is influenced by the individual’s education level, age, gender, occupation, and etc")
st.write('     Purpose: Predict if an individual earns more than $50,000/year.')
st.write('     Source: UCI Machine Learning Repository (available on Kaggle).')
st.write("==============================================================================")
st.write('     1-  age: Age of the individual.')
st.write('     2-  workclass: Type of employment.')
st.write('     3-  fnlwgt: Final weight, used for balancing the data.')
st.write('     4-  education: Highest level of education.')
st.write('     5-  education-num: Number of years of education.')
st.write('     6-  occupation: Type of occupation.')
st.write('     7-  relationship: Relationship to the head of the household. ')
st.write('     8-  race: Race of the individual.')
st.write('     9-  age: Age of the individual.')
st.write('     10- sex: Gender of the individual.')
st.write('     11- capital-gain: Capital gains.')
st.write('     12- capital-loss: Capital losses.')
st.write('     13- hours-per-week: Hours worked per week.')
st.write('     14- native-country: Country of origin.')
st.write("==============================================================================")
st.write('     Target Variable:')
st.write('    *income: Binary indicator if income > $50,000/year (<=50K or >50K).')

st.write('     The income is divide into two classes: <=50K and >50K')

st.write("==============================================================================")
st.write(" Let's Start Our Analysis .... ")
